version: '3.9'

services:
  postgres-users: 
      image: postgres:latest
      environment:
        - POSTGRES_DB=UsersDB
        - POSTGRES_USER=sa
        - POSTGRES_PASSWORD=Your_password123
      ports:
        - "5432:5432"
      networks:
        - backend
      volumes:
        - pg_data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  sql_data:
    driver: local
