version: "3.8"
services:
  # 1. Base de datos principal (la que ya tienes)
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: "EventsDB" # Base de datos general
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "Your_password123"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # 2. Servidor de autenticación
  keycloak-server:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak-server
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 1234
    ports:
      - "8080:8080"

  # 3. Broker de mensajería
  rabbitmq-server:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  # 4. Base de datos documental (para Auditoría)
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  pg_data:
  mongo_data: